apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: core-ingress
spec:
  rules:
    - host: core-{{ .Values.nameSuffix }}.{{ .Values.routingSuffix}}
      http:
        paths:
          - backend:
              serviceName: core
              servicePort: 8080
            path: /entando-sample-app-ekp
          - backend:
              serviceName: core
              servicePort: 8081
            path: /app-builder/
