apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: keycloak
  name: keycloak
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: keycloak
  template:
    metadata:
      labels:
        deployment: keycloak
      name: keycloak-pod
    spec:
      containers:
        - env:
            - name: DB_VENDOR
              value: h2
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /auth
            - name: KEYCLOAK_USER
              value: {{ .Values.keycloakUser }}
            - name: KEYCLOAK_PASSWORD
              value: {{ .Values.keycloakPassword }}
            - name: PROXY_ADDRESS_FORWARDING
              value: 'true'
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dkeycloak.migration.action=import
                -Dkeycloak.migration.provider=singleFile
                -Dkeycloak.migration.file=/etc/keycloak-realm/realm.json
                -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
          image: "docker.io/entando/entando-keycloak:{{ .Values.keycloakImageVersion }}"
          imagePullPolicy: Always
          name: server-container
          ports:
            - containerPort: 8080
              name: server-port
              protocol: TCP
          readinessProbe:
            failureThreshold: 40
            httpGet:
              path: /auth
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 6
            successThreshold: 1
            timeoutSeconds: 3
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/keycloak-realm
              name: keycloak-realm-volume
              readOnly: true
            - mountPath: /opt/jboss/keycloak/standalone/data
              name: keycloak-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - name: keycloak-volume
          persistentVolumeClaim:
            claimName: keycloak-pvc
        - name: keycloak-realm-volume
          configMap:
            defaultMode: 420
            name: keycloak-realm
