apiVersion: v1
kind: Service
metadata:
  labels:
    deployment: keycloak
  name: keycloak
spec:
  ports:
    - name: server-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deployment: keycloak
  type: ClusterIP

